name: warzone2100-videos # no spaces, all lower-case
version: '1'
summary: Campaign video sequences for Warzone 2100
license: GPL-2.0+
description: |
  Campaign video sequences for Warzone 2100
  https://snapcraft.io/warzone2100
  
  See: https://github.com/Warzone2100/warzone2100/blob/master/COPYING.README
confinement: strict
grade: stable
base: bare
build-base: core22
architectures:
  - build-on: [amd64, arm64, armhf]
    build-for: all

slots:
  wz2100-sequences:
    interface: content
    content: wz2100-sequences
    read:
      - $SNAP/data/sequences

parts:
  warzone2100-videos:
    plugin: nil
    source: .
    override-pull: |
      URL1="https://github.com/Warzone2100/wz-sequences/releases/download/v3/high-quality-en-sequences.wz"
      URL2="https://downloads.sourceforge.net/project/warzone2100/warzone2100/Videos/high-quality-en/sequences.wz"
      SHA256Sum="90ff552ca4a70e2537e027e22c5098ea4ed1bc11bb7fc94138c6c941a73d29fa"

      DOWNLOAD_PATH="$CRAFT_PART_SRC/sequences.wz"

      set +e
      $CRAFT_PROJECT_DIR/scripts/FetchAndCheckSHA256.sh "${URL1}" "${DOWNLOAD_PATH}" "${SHA256Sum}"
      result=${?}
      if [ $result -ne 0 ]; then
        echo "warning: Fetching from backup source ..." >&2
        $CRAFT_PROJECT_DIR/scripts/FetchAndCheckSHA256.sh "${URL2}" "${DOWNLOAD_PATH}" "${SHA256Sum}"
        result=${?}
        if [ $result -ne 0 ]; then
          echo "error: Unable to fetch video sequences" >&2
          exit 1
        fi
      fi
    override-build: |
      # Extract sequences.wz
      DOWNLOAD_PATH="$CRAFT_PART_SRC/sequences.wz"
      unzip "${DOWNLOAD_PATH}" -d "$CRAFT_PART_INSTALL/data"
      # Copy COPYING.README
      cp "$CRAFT_PROJECT_DIR/COPYING.README" "$CRAFT_PART_INSTALL/COPYING.README"
    build-packages:
      - bash
      - curl
      - libdigest-sha-perl
      - gawk
      - unzip
