name: Snapcraft

on:
  push:
    branches-ignore:
      - 'l10n_**' # Push events to translation service branches (that begin with "l10n_")
    # Sequence of patterns matched against refs/tags
    tags:
      - '*'
  pull_request:
    # Match all pull requests

permissions:
  contents: read

jobs:
  snapcraft:
    strategy:
      matrix:
        include:
          - name: "Snapcraft"
            arch: "amd64"
    name: '${{ matrix.name }}'
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
    - uses: actions/checkout@v3
    - name: Build .SNAP
      id: snapcraft
      uses: snapcore/action-build@v1
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      if: success()
      with:
        name: 'warzone2100-videos-snap'
        path: '${{ steps.snapcraft.outputs.snap }}'
        if-no-files-found: 'error'
